"""
Trading Data Models

Pydantic models for the auto trading system.
"""

import os
from datetime import datetime
from typing import Optional, Dict, List, Literal
from pydantic import BaseModel, Field


class TradingSignal(BaseModel):
    """Trading signal generated by the agent roundtable"""
    direction: Literal["long", "short", "hold"]
    symbol: str = "BTC-USDT-SWAP"
    leverage: int = Field(ge=1, le=10, default=1)
    amount_percent: float = Field(ge=0, le=1.0, default=0.1)  # 0 for hold, max 100% for trades, validated by RiskLimits
    entry_price: float
    take_profit_price: float
    stop_loss_price: float
    confidence: int = Field(ge=0, le=100)
    reasoning: str
    agents_consensus: Dict[str, str] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.now)

    @property
    def risk_reward_ratio(self) -> float:
        """Calculate risk/reward ratio"""
        if self.direction == "hold":
            return 0.0

        if self.direction == "long":
            risk = abs(self.entry_price - self.stop_loss_price)
            reward = abs(self.take_profit_price - self.entry_price)
        else:  # short
            risk = abs(self.stop_loss_price - self.entry_price)
            reward = abs(self.entry_price - self.take_profit_price)

        return reward / risk if risk > 0 else 0.0


class TradeRecord(BaseModel):
    """Record of an executed trade"""
    id: str
    signal: TradingSignal
    order_id: str
    executed_price: float
    executed_amount: float
    executed_at: datetime
    status: Literal["open", "closed", "cancelled"]
    pnl: Optional[float] = None
    pnl_percent: Optional[float] = None
    close_reason: Optional[Literal["tp", "sl", "manual", "signal"]] = None
    closed_at: Optional[datetime] = None
    closed_price: Optional[float] = None


class Position(BaseModel):
    """Current position information"""
    symbol: str
    direction: Literal["long", "short"]
    size: float
    entry_price: float
    current_price: float
    leverage: int
    unrealized_pnl: float
    unrealized_pnl_percent: float
    take_profit_price: Optional[float] = None
    stop_loss_price: Optional[float] = None
    margin: float
    liquidation_price: float
    opened_at: datetime


class AccountBalance(BaseModel):
    """Account balance information"""
    total_equity: float
    available_balance: float
    used_margin: float
    unrealized_pnl: float
    realized_pnl_today: float
    currency: str = "USDT"
    updated_at: datetime = Field(default_factory=datetime.now)


class EquitySnapshot(BaseModel):
    """Snapshot of account equity for charting"""
    timestamp: datetime
    equity: float
    balance: float
    unrealized_pnl: float
    has_position: bool
    position_direction: Optional[Literal["long", "short"]] = None


class MarketData(BaseModel):
    """Market data for analysis"""
    symbol: str
    price: float
    price_24h_change: float
    volume_24h: float
    high_24h: float
    low_24h: float
    open_24h: float
    funding_rate: Optional[float] = None
    open_interest: Optional[float] = None
    timestamp: datetime = Field(default_factory=datetime.now)


class TechnicalIndicators(BaseModel):
    """Technical indicators for analysis"""
    symbol: str
    timeframe: str
    rsi_14: Optional[float] = None
    macd: Optional[Dict[str, float]] = None  # {macd, signal, histogram}
    bollinger_bands: Optional[Dict[str, float]] = None  # {upper, middle, lower}
    ema_20: Optional[float] = None
    ema_50: Optional[float] = None
    ema_200: Optional[float] = None
    atr_14: Optional[float] = None
    volume_sma_20: Optional[float] = None
    timestamp: datetime = Field(default_factory=datetime.now)


class AgentVote(BaseModel):
    """Individual agent's vote on trading decision"""
    agent_id: str
    agent_name: str
    direction: Literal["long", "short", "hold"]
    confidence: int = Field(ge=0, le=100)
    reasoning: str
    suggested_leverage: int = Field(ge=1, le=10)
    suggested_tp_percent: float
    suggested_sl_percent: float


class TradingSessionState(BaseModel):
    """State of a trading session"""
    session_id: str
    status: Literal["idle", "analyzing", "executing", "monitoring", "error"]
    current_position: Optional[Position] = None
    last_signal: Optional[TradingSignal] = None
    last_trade: Optional[TradeRecord] = None
    next_analysis_at: Optional[datetime] = None
    error_message: Optional[str] = None
    updated_at: datetime = Field(default_factory=datetime.now)


def _get_env_int(key: str, default: int) -> int:
    """Get integer from environment variable"""
    val = os.getenv(key)
    if val:
        try:
            return int(val)
        except ValueError:
            pass
    return default


def _get_env_float(key: str, default: float) -> float:
    """Get float from environment variable"""
    val = os.getenv(key)
    if val:
        try:
            return float(val)
        except ValueError:
            pass
    return default


def _get_env_bool(key: str, default: bool) -> bool:
    """Get boolean from environment variable"""
    val = os.getenv(key)
    if val:
        return val.lower() in ('true', '1', 'yes')
    return default


class RiskLimits(BaseModel):
    """Risk management limits - read from environment variables"""
    max_leverage: int = Field(
        default_factory=lambda: _get_env_int("MAX_LEVERAGE", 20)
    )
    max_position_percent: float = Field(
        default_factory=lambda: _get_env_float("MAX_POSITION_PERCENT", 30) / 100  # Convert to decimal
    )
    min_position_percent: float = Field(
        default_factory=lambda: _get_env_float("MIN_POSITION_PERCENT", 10) / 100  # Convert to decimal
    )
    max_daily_loss_percent: float = 0.1  # 10% daily loss limit
    consecutive_loss_limit: int = Field(
        default_factory=lambda: _get_env_int("MAX_CONSECUTIVE_LOSSES", 3)
    )
    cooldown_hours: int = Field(
        default_factory=lambda: _get_env_int("COOLDOWN_HOURS", 24)
    )
    min_confidence: int = Field(
        default_factory=lambda: _get_env_int("MIN_CONFIDENCE", 60)
    )


class TradingConfig(BaseModel):
    """Trading system configuration"""
    # Read from SCHEDULER_INTERVAL_HOURS env var, default to 4
    analysis_interval_hours: int = Field(
        default_factory=lambda: _get_env_int("SCHEDULER_INTERVAL_HOURS", 4)
    )
    # Read from TRADING_SYMBOL env var
    symbol: str = Field(
        default_factory=lambda: os.getenv("TRADING_SYMBOL", "BTC-USDT-SWAP")
    )
    initial_capital: float = 10000.0
    risk_limits: RiskLimits = Field(default_factory=RiskLimits)
    enabled: bool = True
    demo_mode: bool = Field(
        default_factory=lambda: _get_env_bool("OKX_DEMO_MODE", False)
    )
