"""
Word Report Generator
Word报告生成器

Uses python-docx to generate editable investment analysis reports in Word format.
使用python-docx生成可编辑的投资分析报告Word格式。
"""

from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime
from typing import Dict, Any


class WordReportGenerator:
    """
    Word报告生成器

    Features:
    - 中英文支持
    - 可编辑格式
    - 标题层级
    - 表格和列表
    - 专业样式
    """

    def __init__(self, language: str = "zh"):
        """
        初始化Word生成器

        Args:
            language: 语言 ("zh" 中文, "en" 英文)
        """
        self.language = language
        self.doc = Document()
        self._setup_styles()

    def _setup_styles(self):
        """设置文档样式"""
        # 设置默认字体
        style = self.doc.styles['Normal']
        font = style.font
        font.name = 'Arial'
        font.size = Pt(11)

        # 标题1样式
        style = self.doc.styles['Heading 1']
        style.font.size = Pt(18)
        style.font.bold = True
        style.font.color.rgb = RGBColor(44, 62, 80)

        # 标题2样式
        style = self.doc.styles['Heading 2']
        style.font.size = Pt(14)
        style.font.bold = True
        style.font.color.rgb = RGBColor(52, 73, 94)

        # 标题3样式
        style = self.doc.styles['Heading 3']
        style.font.size = Pt(12)
        style.font.bold = True
        style.font.color.rgb = RGBColor(52, 73, 94)

    def generate_report(
        self,
        report_data: Dict[str, Any],
        output_path: str
    ) -> str:
        """
        生成完整Word报告

        Args:
            report_data: 报告数据
            output_path: 输出文件路径

        Returns:
            生成的Word文件路径
        """
        # 1. 封面
        self._add_cover_page(report_data)
        self.doc.add_page_break()

        # 2. 目录（占位符）
        self._add_table_of_contents()
        self.doc.add_page_break()

        # 3. 执行摘要
        if report_data.get('preliminary_im'):
            self._add_executive_summary(report_data['preliminary_im'])
            self.doc.add_page_break()

        # 4. 财务分析
        if report_data.get('preliminary_im', {}).get('financial_highlights'):
            self._add_financial_section(report_data['preliminary_im'])
            self.doc.add_page_break()

        # 5. 市场分析
        if report_data.get('market_analysis'):
            self._add_market_section(report_data['market_analysis'])
            self.doc.add_page_break()

        # 6. 团队分析
        if report_data.get('team_analysis'):
            self._add_team_section(report_data['team_analysis'])
            self.doc.add_page_break()

        # 7. 风险评估
        if report_data.get('preliminary_im', {}).get('risks'):
            self._add_risk_section(report_data['preliminary_im'])
            self.doc.add_page_break()

        # 8. 结论和建议
        if report_data.get('preliminary_im'):
            self._add_conclusion(report_data['preliminary_im'])

        # 保存文档
        self.doc.save(output_path)
        return output_path

    def _add_cover_page(self, report_data: Dict[str, Any]):
        """添加封面"""
        # 标题
        if self.language == "en":
            title = "Investment Analysis Report"
            subtitle = report_data.get('company_name', 'Company Name')
        else:
            title = "投资尽职调查报告"
            subtitle = report_data.get('company_name', '公司名称')

        title_para = self.doc.add_paragraph(title)
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_run = title_para.runs[0]
        title_run.font.size = Pt(24)
        title_run.font.bold = True

        self.doc.add_paragraph()  # 空行

        subtitle_para = self.doc.add_paragraph(subtitle)
        subtitle_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        subtitle_run = subtitle_para.runs[0]
        subtitle_run.font.size = Pt(18)
        subtitle_run.font.bold = True

        # 添加空行
        for _ in range(5):
            self.doc.add_paragraph()

        # 日期
        date_str = datetime.now().strftime("%Y-%m-%d")
        if self.language == "en":
            date_text = f"Report Date: {date_str}"
        else:
            date_text = f"报告日期: {date_str}"

        date_para = self.doc.add_paragraph(date_text)
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # 生成信息
        self.doc.add_paragraph()
        if self.language == "en":
            gen_text = "Generated by Magellan AI Investment Analysis Platform"
        else:
            gen_text = "由 Magellan AI 投资分析平台生成"

        gen_para = self.doc.add_paragraph(gen_text)
        gen_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    def _add_table_of_contents(self):
        """添加目录"""
        if self.language == "en":
            self.doc.add_heading("Table of Contents", level=1)
        else:
            self.doc.add_heading("目录", level=1)

        sections = []
        if self.language == "en":
            sections = [
                "1. Executive Summary",
                "2. Financial Analysis",
                "3. Market Analysis",
                "4. Team Assessment",
                "5. Risk Evaluation",
                "6. Conclusion and Recommendations"
            ]
        else:
            sections = [
                "1. 执行摘要",
                "2. 财务分析",
                "3. 市场分析",
                "4. 团队评估",
                "5. 风险评估",
                "6. 结论与建议"
            ]

        for section in sections:
            self.doc.add_paragraph(section, style='List Bullet')

    def _add_executive_summary(self, im_data: Dict[str, Any]):
        """添加执行摘要"""
        if self.language == "en":
            self.doc.add_heading("1. Executive Summary", level=1)
        else:
            self.doc.add_heading("1. 执行摘要", level=1)

        # 投资建议
        if im_data.get('investment_recommendation'):
            if self.language == "en":
                self.doc.add_heading("Investment Recommendation", level=2)
            else:
                self.doc.add_heading("投资建议", level=2)

            self.doc.add_paragraph(str(im_data['investment_recommendation']))

        # 关键发现
        if im_data.get('key_findings'):
            if self.language == "en":
                self.doc.add_heading("Key Findings", level=2)
            else:
                self.doc.add_heading("关键发现", level=2)

            findings = im_data['key_findings']
            if isinstance(findings, list):
                for finding in findings:
                    if isinstance(finding, dict):
                        # Format dict finding
                        category = finding.get('category', 'General')
                        score = finding.get('score', 'N/A')
                        points = "; ".join(finding.get('key_points', []))
                        concerns = "; ".join(finding.get('concerns', []))
                        
                        text = f"{category} (评分: {score})"
                        if points: text += f" - 亮点: {points}"
                        if concerns: text += f" - 关注: {concerns}"
                        
                        self.doc.add_paragraph(text, style='List Bullet')
                    else:
                        self.doc.add_paragraph(str(finding), style='List Bullet')
            else:
                self.doc.add_paragraph(str(findings))

        # 投资亮点
        if im_data.get('investment_highlights'):
            if self.language == "en":
                self.doc.add_heading("Investment Highlights", level=2)
            else:
                self.doc.add_heading("投资亮点", level=2)

            highlights = im_data['investment_highlights']
            if isinstance(highlights, list):
                for hl in highlights:
                    self.doc.add_paragraph(str(hl), style='List Bullet')
            else:
                self.doc.add_paragraph(str(highlights))

    def _add_financial_section(self, im_data: Dict[str, Any]):
        """添加财务分析章节"""
        if self.language == "en":
            self.doc.add_heading("2. Financial Analysis", level=1)
        else:
            self.doc.add_heading("2. 财务分析", level=1)

        fin_data = im_data.get('financial_highlights', {})

        if fin_data:
            if self.language == "en":
                self.doc.add_heading("Financial Highlights", level=2)
            else:
                self.doc.add_heading("财务亮点", level=2)

            # 创建表格
            table = self.doc.add_table(rows=1, cols=2)
            table.style = 'Light Grid Accent 1'

            # 表头
            if self.language == "en":
                hdr_cells = table.rows[0].cells
                hdr_cells[0].text = 'Metric'
                hdr_cells[1].text = 'Value'
            else:
                hdr_cells = table.rows[0].cells
                hdr_cells[0].text = '指标'
                hdr_cells[1].text = '数值'

            # 数据行
            for key, value in fin_data.items():
                row_cells = table.add_row().cells
                row_cells[0].text = str(key)
                row_cells[1].text = str(value)

        # 财务分析
        if im_data.get('financial_analysis'):
            if self.language == "en":
                self.doc.add_heading("Analysis", level=2)
            else:
                self.doc.add_heading("分析", level=2)

            self.doc.add_paragraph(str(im_data['financial_analysis']))

    def _add_market_section(self, market_data: Dict[str, Any]):
        """添加市场分析章节"""
        if self.language == "en":
            self.doc.add_heading("3. Market Analysis", level=1)
        else:
            self.doc.add_heading("3. 市场分析", level=1)

        # 市场规模
        if market_data.get('market_size_analysis'):
            if self.language == "en":
                self.doc.add_heading("Market Size", level=2)
            else:
                self.doc.add_heading("市场规模", level=2)

            self.doc.add_paragraph(str(market_data['market_size_analysis']))

        # 竞争格局
        if market_data.get('competitive_landscape'):
            if self.language == "en":
                self.doc.add_heading("Competitive Landscape", level=2)
            else:
                self.doc.add_heading("竞争格局", level=2)

            self.doc.add_paragraph(str(market_data['competitive_landscape']))

        # 市场趋势
        if market_data.get('market_trends'):
            if self.language == "en":
                self.doc.add_heading("Market Trends", level=2)
            else:
                self.doc.add_heading("市场趋势", level=2)

            trends = market_data['market_trends']
            if isinstance(trends, list):
                for trend in trends:
                    self.doc.add_paragraph(str(trend), style='List Bullet')
            else:
                self.doc.add_paragraph(str(trends))

    def _add_team_section(self, team_data: Dict[str, Any]):
        """添加团队分析章节"""
        if self.language == "en":
            self.doc.add_heading("4. Team Assessment", level=1)
        else:
            self.doc.add_heading("4. 团队评估", level=1)

        # 团队评分
        if team_data.get('experience_match_score'):
            if self.language == "en":
                score_text = f"Experience Match Score: {team_data['experience_match_score']}/10"
            else:
                score_text = f"经验匹配度评分: {team_data['experience_match_score']}/10"

            para = self.doc.add_paragraph(score_text)
            para.runs[0].font.bold = True
            para.runs[0].font.color.rgb = RGBColor(231, 76, 60)

        # 团队优势
        if team_data.get('strengths'):
            if self.language == "en":
                self.doc.add_heading("Team Strengths", level=2)
            else:
                self.doc.add_heading("团队优势", level=2)

            strengths = team_data['strengths']
            if isinstance(strengths, list):
                for strength in strengths:
                    self.doc.add_paragraph(str(strength), style='List Bullet')
            else:
                self.doc.add_paragraph(str(strengths))

        # 改进建议
        if team_data.get('recommendations'):
            if self.language == "en":
                self.doc.add_heading("Recommendations", level=2)
            else:
                self.doc.add_heading("改进建议", level=2)

            recs = team_data['recommendations']
            if isinstance(recs, list):
                for rec in recs:
                    self.doc.add_paragraph(str(rec), style='List Bullet')
            else:
                self.doc.add_paragraph(str(recs))

    def _add_risk_section(self, im_data: Dict[str, Any]):
        """添加风险评估章节"""
        if self.language == "en":
            self.doc.add_heading("5. Risk Evaluation", level=1)
        else:
            self.doc.add_heading("5. 风险评估", level=1)

        risks = im_data.get('risks', [])
        if isinstance(risks, list):
            for risk in risks:
                if isinstance(risk, dict):
                    risk_name = risk.get('name', 'Unknown Risk')
                    risk_level = risk.get('level', 'Unknown')
                    risk_desc = risk.get('description', '')

                    self.doc.add_heading(f"{risk_name} ({risk_level})", level=3)
                    if risk_desc:
                        self.doc.add_paragraph(risk_desc)
                else:
                    self.doc.add_paragraph(str(risk), style='List Bullet')
        else:
            self.doc.add_paragraph(str(risks))

    def _add_conclusion(self, im_data: Dict[str, Any]):
        """添加结论章节"""
        if self.language == "en":
            self.doc.add_heading("6. Conclusion and Recommendations", level=1)
        else:
            self.doc.add_heading("6. 结论与建议", level=1)

        # 最终建议
        if im_data.get('final_recommendation'):
            if self.language == "en":
                self.doc.add_heading("Final Recommendation", level=2)
            else:
                self.doc.add_heading("最终建议", level=2)

            self.doc.add_paragraph(str(im_data['final_recommendation']))

        # 下一步行动
        if im_data.get('next_steps'):
            if self.language == "en":
                self.doc.add_heading("Next Steps", level=2)
            else:
                self.doc.add_heading("下一步行动", level=2)

            next_steps = im_data['next_steps']
            if isinstance(next_steps, list):
                for step in next_steps:
                    self.doc.add_paragraph(str(step), style='List Bullet')
            else:
                self.doc.add_paragraph(str(next_steps))

        # 免责声明
        self.doc.add_paragraph()
        if self.language == "en":
            disclaimer = ("This report is generated by AI and should be used for reference only. "
                        "Please conduct thorough due diligence before making investment decisions.")
        else:
            disclaimer = "本报告由AI生成，仅供参考。投资决策前请进行全面的尽职调查。"

        para = self.doc.add_paragraph(disclaimer)
        para.runs[0].font.italic = True
        para.runs[0].font.size = Pt(10)


# 便捷函数
def generate_word_report(
    report_data: Dict[str, Any],
    output_path: str,
    language: str = "zh"
) -> str:
    """
    生成Word报告的便捷函数

    Args:
        report_data: 报告数据
        output_path: 输出文件路径
        language: 语言设置

    Returns:
        生成的Word文件路径
    """
    generator = WordReportGenerator(language=language)
    return generator.generate_report(report_data, output_path)
